### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by caoxu915683474** [Thanatine/Neural-Machine-Translation#2]
Hi, thanks for your great project!
I have some questions about these two lines.
so, why  do you use tf.identity() and what is the difference between predicted_ids and sample_is.
can you help me, thank you!
 
`self.decoder_predictions_inference = tf.identity(self.decoder_outputs_inference.predicted_ids)`
`self.decoder_predictions_inference = tf.identity(self.decoder_outputs_inference.sample_id)`

**Comment by tommykwh** [comment]
Hi Cao,

Thanks for the tryout!

1. Why use tf.identity()
It's only for the sake of convenience and readability.
(At least I couldn't remember any other reason for now lol)

2. Difference between `predicted_ids` and `sample_id`
The major difference is due to they are actually outputs of different classes, 
[`BasicDecoderOutput`](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/BasicDecoderOutput) and [`BeamSearchDecoderOutput`](https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/BeamSearchDecoderOutput), 
and they are composed of different properties.
The shapes of these two are different too. (beamsearch decoder's output start with [beam_width ...])

Hope these clarify your questions.
Thanks!

**Comment by caoxu915683474** [comment]
Thanks for your quick help, it really helps me!
